"""Instrument frozen v022 routines for diagnosis on saved schedules only."""
from pathlib import Path

root = Path(__file__).resolve().parents[2]
source = (root / "src/bin/v022_dependency_lns.cpp").read_text()
source = source[:source.rindex("int main(")]
source = source.replace("class TemporalLNS {", """
struct InsertProfile {
    double setup=0, spatial=0, event=0, seed=0, reconstruct=0;
    int64_t layers=0, scanned=0, eligible=0;
} insert_profile;
using ProfileClock = chrono::steady_clock;
double profile_ns(ProfileClock::time_point start) {
    return chrono::duration<double,nano>(ProfileClock::now()-start).count();
}
class TemporalLNS {""")
start = source.index("    bool insertAt(")
end = source.index("    bool insert(const Board&", start)
part = source[start:end]
part = part.replace("LOCAL_NOTE(++local_single_insert_calls;)",
                    "LOCAL_NOTE(++local_single_insert_calls;)\n        auto section_start=ProfileClock::now();")
part = part.replace("int q=geo.ray[p][d][l];\n                if(h[q]<8&&l<=h[q]+1)seed(q);",
                    "int q=geo.ray[p][d][l];++insert_profile.scanned;\n                if(h[q]<8&&l<=h[q]+1){++insert_profile.eligible;seed(q);}")
part = part.replace("        seed(source);", "        seed(source);insert_profile.setup+=profile_ns(section_start);")
part = part.replace("            int pops=0,queuedPosition,queuedCost;",
                    "            section_start=ProfileClock::now();\n            int pops=0,queuedPosition,queuedCost;")
part = part.replace("            if(t==int(base.size()))break;", "            insert_profile.spatial+=profile_ns(section_start);\n            if(t==int(base.size()))break;\n            section_start=ProfileClock::now();")
part = part.replace("            seedNeighborhood(p,reopenP);seedNeighborhood(q,reopenQ);", "            insert_profile.event+=profile_ns(section_start);\n            section_start=ProfileClock::now();\n            seedNeighborhood(p,reopenP);seedNeighborhood(q,reopenQ);\n            insert_profile.seed+=profile_ns(section_start);++insert_profile.layers;")
part = part.replace("        result=reconstruct(base,label[GOAL].path);", "        section_start=ProfileClock::now();\n        result=reconstruct(base,label[GOAL].path);\n        insert_profile.reconstruct+=profile_ns(section_start);")
source = source[:start] + part + source[end:]
driver = (root / "adhoc/v024_profile_driver.inc").read_text()
out = root / "adhoc/bin/profile_v024_reinsertion.cpp"
out.write_text("// profile_v024_reinsertion.cpp\n// Generated by prepare_v024_profile.py; does not run the optimizer.\n" + source + driver)
